# https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/examples/kafka/kafka-persistent.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.cluster_name }}
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.brokers }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage_size }}
        deleteClaim: false
    metricsConfig:	
      type: jmxPrometheusExporter	
      valueFrom:	
        configMapKeyRef:	
          key: kafka-metrics-config.yml	
          name: kafka-metrics-{{ .Values.clusterName }}
  kafkaExporter:	
    groupRegex: .*	
    topicRegex: .*
  zookeeper:
    version: {{ .Values.zookeeper.version }}
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage_size }}
      deleteClaim: false
    metricsConfig:	
      type: jmxPrometheusExporter	
      valueFrom:	
        configMapKeyRef:	
          key: zookeeper-metrics-config.yml	
          name: kafka-metrics-{{ .Values.clusterName }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
